<form method="post">
	<h2>Disclaimer</h2>
	This application is still <b>a work in progress</b>. It is currently functional but still being worked on in order to make this application as stable as possible.<br>
	During the registration process, you are required to authorize this application to your Twitter account and your access tokens will be stored in the database. These tokens will <b>never</b> be misused.<br>
	In a scenario where these tokens get compromised, you <b>must</b> revoke this application access right away to keep your Twitter account safe.<br>
	<br>
	By agreeing to these terms, you will also agree to opt-in to testing this application and <b>to use it by your own risk</b>. You are also helping out this project by testing it.<br>
	I will not take responsibility for any damage done by this application. This application is <b>not 100% stable</b> yet.<br>
	<br>
	<input type="submit" value="I agree"><br>
	<input type="hidden" name="agreement" value="1">
</form>