<hr>
A total of <?php echo $usercount ?> different users have used this application.<br>
Source code is now available at <a href="https://github.com/Frizz925/osuautorecent">GitHub</a>.<br>
Found a bug or issue? Report it <a href="https://github.com/Frizz925/osuautorecent/issues">here</a>!<br>
<span style="font-size: 11px;">Sshh... need to remove your tokens? Go <a href="./remove">here</a>!</span><br>