<html>
	<head>
		<title>osu! Automated Recent Activity Tweet</title>
		<link href="main.css" rel="stylesheet" type="text/css">
		<script>
			window.onload = setTimeout(function() { window.location = "./index.php" }, 3000)
		</script>
	</head>
	<body>
		<div class="wrapper">
			<h1>osu! Automated Recent Activity Tweet</h1>
			<?php print_r($content); ?><br>
			You will be automatically redirected back to the homepage.
		</div>
	</body>
</html>